apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
  labels:
    app: book-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: book-catalog
        image: kuzmin35/book-catalog:0.0.1-SNAPSHOT
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5" ]
        ports:
        - containerPort: 9001
        env:
          - name: SPRING_DATA_MONGODB_HOST
            value: book-catalog-mongodb
          - name: SPRING_DATA_MONGODB_PORT
            value: "27017"
          - name: SPRING_DATA_MONGODB_DATABASE
            value: book-catalog
          - name: SPRING_DATA_MONGODB_USERNAME
            value: user
          - name: SPRING_DATA_MONGODB_PASSWORD
            value: password
        resources:
          requests:
            memory: "756Mi"
            cpu: "0.5"
          limits:
            memory: "756Mi"